select f_name,l_name from student;
select course_name from courses;
select count (*) from classroom;
 select building_name,count(*) from classroom group by building_name;
select teacher_name from teacher;
 select classroom_no from classroom where classroom_no<>103;select course_name from courses where course_name like '%l%';
select course_name, count (distinct course_name)from courses group by course_name;
 select count (distinct course_name)from courses;
select course_name, count (course_name)from courses group by course_name;
select department_name from department where department_id=12;
select max(department_id) from department;
select department_name from department where department_id<20;
select Email_id from procedure where device='mobile' or software='zoom';
 select  avg(age) as avg_age from student;
select age from student where age<>(select max (age)from student);
select max( age) from student where age<>(select max (age)from student);
select distinct student_id, f_name,l_name,date_of_birth,age from student;
select f_name from student where student_id=1001 AND age=21;
select email_id,device from procedure;
SELECT STUDENT.F_NAME,DEPARTMENT.DEPARTMENT_NAME FROM STUDENT INNER JOIN  DEPARTMENT ON STUDENT.STUDENT_ID = DEPARTMENT.DEPARTMENT_ID;
SELECT STUDENT.F_NAME,procedure.Device FROM STUDENT INNER JOIN  procedure ON STUDENT.STUDENT_ID = procedure.p_ID;
SELECT STUDENT.F_NAME,procedure.Device, procedure.email_id,procedure.software FROM STUDENT INNER JOIN  procedure ON STUDENT.STUDENT_ID = procedure.p_ID;
select count(student_id) from student;
select f_name,l_name from student where f_name like '%a' or l_name like '%a' ;
delete from student where student_id=1001;
select * from tab;
 describe procedure;
 update student set f_name='rima' where student_id=1001 and l_name='rahman';
 select min(age) from student;